# Generated by Django 3.1.3 on 2020-11-09 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bangladesh',
            fields=[
                ('objectid', models.AutoField(db_column='OBJECTID', primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('adm2_en', models.CharField(blank=True, max_length=50, null=True)),
                ('adm2_pcode', models.CharField(blank=True, max_length=50, null=True)),
                ('adm2_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('adm2alt1en', models.CharField(blank=True, max_length=50, null=True)),
                ('adm2alt2en', models.CharField(blank=True, max_length=50, null=True)),
                ('adm1_en', models.CharField(blank=True, max_length=50, null=True)),
                ('adm1_pcode', models.CharField(blank=True, max_length=50, null=True)),
                ('adm0_en', models.CharField(blank=True, max_length=50, null=True)),
                ('adm0_pcode', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('validon', models.DateField(blank=True, null=True)),
                ('validto', models.DateField(blank=True, null=True)),
                ('objectid_0', models.BigIntegerField(blank=True, db_column='objectid', null=True)),
            ],
            options={
                'db_table': 'bangladesh',
                'managed': False,
            },
        ),
    ]
