# Generated by Django 3.1.3 on 2020-12-06 09:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sodesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('area_bigha', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('katha', models.CharField(blank=True, max_length=20, null=True)),
                ('plot_type', models.CharField(blank=True, max_length=20, null=True)),
                ('area_k', models.CharField(blank=True, max_length=20, null=True)),
                ('dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('plot_no', models.CharField(blank=True, max_length=50, null=True)),
                ('katha_1', models.CharField(blank=True, max_length=20, null=True)),
                ('road_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_field', models.CharField(blank=True, db_column='father__', max_length=50, null=True)),
                ('spouse_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('national_i', models.BigIntegerField(blank=True, null=True)),
                ('tin_field', models.BigIntegerField(blank=True, db_column='tin___', null=True)),
                ('land_price', models.BigIntegerField(blank=True, null=True)),
                ('mou_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mou_jl', models.CharField(blank=True, max_length=50, null=True)),
                ('pur_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('inst_date', models.DateField(blank=True, null=True)),
                ('new', models.IntegerField(blank=True, null=True)),
                ('land_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('road', models.CharField(blank=True, max_length=50, null=True)),
                ('id_new', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sodesh',
                'managed': False,
            },
        ),
    ]
